language: swift
os: osx

before_install:
  - brew install carthage
  - gem install cocoapods
  - pod install

before_script:
  - carthage bootstrap --platform iOS

script:
  - xcodebuild test -workspace lunchFinderIOS.xcworkspace -scheme lunchFinderIOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2'
